import aiohttp
import asyncio
import time

async def fetchIDs(namelist):    
    async def fetch(session, url, name):
        params = [
            ('categories', 'character'), 
            ('datasource', 'tranquility'), 
            ('language', 'en-us'), 
            ('search', name),
            ('strict', 'true')]

        async with session.get(url, params=params) as response:
            data = await response.json()
            return {"name":name, "charID": data['character'][0]}

    async def fetch_all(name_list):
        url = 'https://esi.evetech.net/latest/search/'
        async with aiohttp.ClientSession() as session:
            results = await asyncio.gather(*[fetch(session, url, name) for name in name_list], return_exceptions=True)
            return results

    return await fetch_all(namelist)

async def fetch_charData(charID_list):    
    async def fetch(session, charID):
        params = [
            ('datasource', 'tranquility'), 
        ]
        url = 'https://esi.evetech.net/latest/characters/'
        async with session.get(url + str(charID), params=params) as response:
            return await response.json()

    async def fetch_all(charID_list):
        async with aiohttp.ClientSession() as session:
            results = await asyncio.gather(*[fetch(session, entry['charID']) for entry in charID_list], return_exceptions=True)
            return results

    return await fetch_all(charID_list)

async def full_fetch(namelist):
    ids = await fetchIDs(namelist)
    data = await fetch_charData(ids)
    return data

if __name__ == "__main__":
    names = [
        "aboc cheeze",
        "Adam Zamoyski",
        "Adds Hendar",
        "Aegaeonos",
        "Aeleria Mikuyo",
        "Airaim",
        "Akhubkhan Darksky",
        "Alcoholic Satan",
        "Aleria Darwin",
        "Ambrosius Aurelianus",
        "angelfr",
        "Apostle McHouse",
        "Armos Dragoon",
        "Aurynn Elarik",
        "Ayu Kasenumi",
        "Bakkachan",
        "Barnabus Sanders",
        "BaseEight Chelien",
        "Bassdusche ZiggyX",
        "Bingo Bongoed",
        "Boot",
        "Burk DETEIS",
        "caleb ball",
        "Calypso72 303",
        "Candy Cough-Drop",
        "Cap Skor",
        "Capt Jack Daniels",
        "CeeCee Weebus",
        "Champagne Hennessy",
        "Chaplain''Dextomus",
        "Choc Starfish",
        "Chris Griffin",
        "Clam Chowdah",
        "Cmdr Stargazer",
        "Colt Sauer",
        "crowtree",
        "Daemon Hawke",
        "Dameonirus Marino",
        "Darklord Dvader",
        "Darklord Tarkin",
        "Dean Snow",
        "DexProcter Bedala",
        "Djorr",
        "Draco McHouse",
        "Draison Foul",
        "Duke Swackhammer",
        "Dusty Deninard",
        "Ejen Nailo",
        "Elimination2",
        "Ellse Kryan",
        "EmperorFry",
        "Entriri Crendraven",
        "Esinhart Ohmiras",
        "Exogenic",
        "Eydoriane Cloudrider",
        "FakePresident Trump",
        "Farah Al Assad",
        "Faridah",
        "Fisto's Judgement",
        "Fleeny theYounger",
        "Franklin Underhill",
        "Franky Stien",
        "Freeto",
        "Gell Schereau",
        "Goro Nobunaga",
        "gritchack",
        "Gruara Ambrye",
        "Hadra Moot",
        "Haha Doodskop",
        "Hans toker",
        "Heilfr Cfidard",
        "Hippo117",
        "Hoe Hum",
        "Hollygun",
        "Honor Treecat",
        "Ilian Amarin",
        "Iliana Amphal",
        "ImArchy",
        "Iroha Ramalho",
        "Ismael Zambada Garcia",
        "ivan noskoov",
        "Iymyrr D'Harun",
        "Jace Firemind",
        "Jakaja Cain",
        "Jeff Jayson",
        "JFKen Imperia",
        "Jin mung",
        "Johan Vilhelmsson",
        "Johnny Trousersnake",
        "Jordan Atavuli",
        "Jordan Clarksonton",
        "Jordan Lafisques",
        "Kal Flindor",
        "Kalo en Chasteaux",
        "Katakuri Ramalho",
        "Kemalmus",
        "Ketldor Ashokan",
        "Khaelian Osiris",
        "Khan'nikki",
        "Kheironos",
        "Koursk",
        "Krab Star",
        "Kurt Knispel",
        "Larry Scuttlebutt",
        "Latif Noban",
        "Le Farf",
        "Le limier",
        "lei Sinulf",
        "Liloo Metarkonnen",
        "Lucius Servius",
        "Ludwig Timewax",
        "Maiandra",
        "makstomaks",
        "Malken Odunen",
        "Maruda",
        "Matt L Hendar",
        "Mc Crecket",
        "MechaJeb Kerman",
        "Meemee Weebus",
        "Mickey Ultama",
        "Mist Amatin",
        "Miws Vokan",
        "Mora Repsonme",
        "Morghul Olon",
        "Mr Amezes Oramara",
        "Myon Acryllic",
        "Myon PogChamp",
        "Myon Valestoft",
        "n-Kada Booya",
        "Nira Marie",
        "No Thing",
        "Noisy Pink Bubbles",
        "ob1canoby-OG ONLY-OB1",
        "Omnipotent Cortex",
        "OneMan DeathSquad",
        "Orice",
        "Overcheles",
        "Pabby Lasoya",
        "Paul Brinkhoff",
        "Paymaster General Sacrosanct",
        "PikkuLissu",
        "Price Point",
        "pscyho",
        "Queen Gaea",
        "Quinn Dorsey",
        "Rainear Xanatos",
        "Ralphy Ari",
        "Randy Antollare",
        "Rath Windblade",
        "rdmr",
        "redmanic",
        "Renalus Darwin",
        "Rob-Halford",
        "robert hunt1",
        "Rocinantae",
        "Rock Lobster Larry",
        "Rock Triel",
        "Rodger Mueller",
        "Roy Underhill",
        "Runoff",
        "rupert man",
        "Sam Caldwel",
        "Sarebey",
        "Schneemann",
        "Sevara",
        "Shadow Bogspor",
        "Shinn Fumimasa",
        "Shpuntik",
        "sidoradan Eginald",
        "Simo Kehveli",
        "Skye Raiden",
        "Skyline9982 Aucie",
        "Soft Night",
        "Sonto Mikakka",
        "sourcey1",
        "Spooky Azaphi",
        "Spooky Emabali",
        "Sprinkle's McGee",
        "SPT2",
        "Square Error",
        "stopdropandlol",
        "Stormborn Runoff",
        "Strata McHouse",
        "Surprise Dreads",
        "Teetee Weebus",
        "Tekno Hunter",
        "tenned ekul",
        "Thaiax Isu",
        "The Cincinnati Twiz",
        "Thelzar Calzahar",
        "Theodore James",
        "Thrain Greyrider",
        "Thraun Ravensoul",
        "Throck Wallace",
        "Thyme Trader",
        "Tohu Tohuwabohu",
        "TracKBalL",
        "Uppsala",
        "Urodela Andomer",
        "Valda Varugashi",
        "Vandamsel",
        "Vera McCoy",
        "Volp Elysian",
        "Wex Starstryker",
        "wiliam Aldent",
        "Wolf Doukas",
        "yaabaa Onnlin",
        "Yasmine72",
        "Zarik Arafax",
        "Zawahir",
        "Zhele Jamohrr",
        "zinox Yadekfic",
        "aboc cheeze",
        "Adam Zamoyski",
        "Adds Hendar",
        "Aegaeonos",
        "Aeleria Mikuyo",
        "Airaim",
        "Akhubkhan Darksky",
        "Alcoholic Satan",
        "Aleria Darwin",
        "Ambrosius Aurelianus",
        "angelfr",
        "Apostle McHouse",
        "Armos Dragoon",
        "Aurynn Elarik",
        "Ayu Kasenumi",
        "Bakkachan",
        "Barnabus Sanders",
        "BaseEight Chelien",
        "Bassdusche ZiggyX",
        "Bingo Bongoed",
        "Boot",
        "Burk DETEIS",
        "caleb ball",
        "Calypso72 303",
        "Candy Cough-Drop",
        "Cap Skor",
        "Capt Jack Daniels",
        "CeeCee Weebus",
        "Champagne Hennessy",
        "Chaplain''Dextomus",
        "Choc Starfish",
        "Chris Griffin",
        "Clam Chowdah",
        "Cmdr Stargazer",
        "Colt Sauer",
        "crowtree",
        "Daemon Hawke",
        "Dameonirus Marino",
        "Darklord Dvader",
        "Darklord Tarkin",
        "Dean Snow",
        "DexProcter Bedala",
        "Djorr",
        "Draco McHouse",
        "Draison Foul",
        "Duke Swackhammer",
        "Dusty Deninard",
        "Ejen Nailo",
        "Elimination2",
        "Ellse Kryan",
        "EmperorFry",
        "Entriri Crendraven",
        "Esinhart Ohmiras",
        "Exogenic",
        "Eydoriane Cloudrider",
        "FakePresident Trump",
        "Farah Al Assad",
        "Faridah",
        "Fisto's Judgement",
        "Fleeny theYounger",
        "Franklin Underhill",
        "Franky Stien",
        "Freeto",
        "Gell Schereau",
        "Goro Nobunaga",
        "gritchack",
        "Gruara Ambrye",
        "Hadra Moot",
        "Haha Doodskop",
        "Hans toker",
        "Heilfr Cfidard",
        "Hippo117",
        "Hoe Hum",
        "Hollygun",
        "Honor Treecat",
        "Ilian Amarin",
        "Iliana Amphal",
        "ImArchy",
        "Iroha Ramalho",
        "Ismael Zambada Garcia",
        "ivan noskoov",
        "Iymyrr D'Harun",
        "Jace Firemind",
        "Jakaja Cain",
        "Jeff Jayson",
        "JFKen Imperia",
        "Jin mung",
        "Johan Vilhelmsson",
        "Johnny Trousersnake",
        "Jordan Atavuli",
        "Jordan Clarksonton",
        "Jordan Lafisques",
        "Kal Flindor",
        "Kalo en Chasteaux",
        "Katakuri Ramalho",
        "Kemalmus",
        "Ketldor Ashokan",
        "Khaelian Osiris",
        "Khan'nikki",
        "Kheironos",
        "Koursk",
        "Krab Star",
        "Kurt Knispel",
        "Larry Scuttlebutt",
        "Latif Noban",
        "Le Farf",
        "Le limier",
        "lei Sinulf",
        "Liloo Metarkonnen",
        "Lucius Servius",
        "Ludwig Timewax",
        "Maiandra",
        "makstomaks",
        "Malken Odunen",
        "Maruda",
        "Matt L Hendar",
        "Mc Crecket",
        "MechaJeb Kerman",
        "Meemee Weebus",
        "Mickey Ultama",
        "Mist Amatin",
        "Miws Vokan",
        "Mora Repsonme",
        "Morghul Olon",
        "Mr Amezes Oramara",
        "Myon Acryllic",
        "Myon PogChamp",
        "Myon Valestoft",
        "n-Kada Booya",
        "Nira Marie",
        "No Thing",
        "Noisy Pink Bubbles",
        "ob1canoby-OG ONLY-OB1",
        "Omnipotent Cortex",
        "OneMan DeathSquad",
        "Orice",
        "Overcheles",
        "Pabby Lasoya",
        "Paul Brinkhoff",
        "Paymaster General Sacrosanct",
        "PikkuLissu",
        "Price Point",
        "pscyho",
        "Queen Gaea",
        "Quinn Dorsey",
        "Rainear Xanatos",
        "Ralphy Ari",
        "Randy Antollare",
        "Rath Windblade",
        "rdmr",
        "redmanic",
        "Renalus Darwin",
        "Rob-Halford",
        "robert hunt1",
        "Rocinantae",
        "Rock Lobster Larry",
        "Rock Triel",
        "Rodger Mueller",
        "Roy Underhill",
        "Runoff",
        "rupert man",
        "Sam Caldwel",
        "Sarebey",
        "Schneemann",
        "Sevara",
        "Shadow Bogspor",
        "Shinn Fumimasa",
        "Shpuntik",
        "sidoradan Eginald",
        "Simo Kehveli",
        "Skye Raiden",
        "Skyline9982 Aucie",
        "Soft Night",
        "Sonto Mikakka",
        "sourcey1",
        "Spooky Azaphi",
        "Spooky Emabali",
        "Sprinkle's McGee",
        "SPT2",
        "Square Error",
        "stopdropandlol",
        "Stormborn Runoff",
        "Strata McHouse",
        "Surprise Dreads",
        "Teetee Weebus",
        "Tekno Hunter",
        "tenned ekul",
        "Thaiax Isu",
        "The Cincinnati Twiz",
        "Thelzar Calzahar",
        "Theodore James",
        "Thrain Greyrider",
        "Thraun Ravensoul",
        "Throck Wallace",
        "Thyme Trader",
        "Tohu Tohuwabohu",
        "TracKBalL",
        "Uppsala",
        "Urodela Andomer",
        "Valda Varugashi",
        "Vandamsel",
        "Vera McCoy",
        "Volp Elysian",
        "Wex Starstryker",
        "wiliam Aldent",
        "Wolf Doukas",
        "yaabaa Onnlin",
        "Yasmine72",
        "Zarik Arafax",
        "Zawahir",
        "Zhele Jamohrr",
        "zinox Yadekfic",
        "aboc cheeze",
        "Adam Zamoyski",
        "Adds Hendar",
        "Aegaeonos",
        "Aeleria Mikuyo",
        "Airaim",
        "Akhubkhan Darksky",
        "Alcoholic Satan",
        "Aleria Darwin",
        "Ambrosius Aurelianus",
        "angelfr",
        "Apostle McHouse",
        "Armos Dragoon",
        "Aurynn Elarik",
        "Ayu Kasenumi",
        "Bakkachan",
        "Barnabus Sanders",
        "BaseEight Chelien",
        "Bassdusche ZiggyX",
        "Bingo Bongoed",
        "Boot",
        "Burk DETEIS",
        "caleb ball",
        "Calypso72 303",
        "Candy Cough-Drop",
        "Cap Skor",
        "Capt Jack Daniels",
        "CeeCee Weebus",
        "Champagne Hennessy",
        "Chaplain''Dextomus",
        "Choc Starfish",
        "Chris Griffin",
        "Clam Chowdah",
        "Cmdr Stargazer",
        "Colt Sauer",
        "crowtree",
        "Daemon Hawke",
        "Dameonirus Marino",
        "Darklord Dvader",
        "Darklord Tarkin",
        "Dean Snow",
        "DexProcter Bedala",
        "Djorr",
        "Draco McHouse",
        "Draison Foul",
        "Duke Swackhammer",
        "Dusty Deninard",
        "Ejen Nailo",
        "Elimination2",
        "Ellse Kryan",
        "EmperorFry",
        "Entriri Crendraven",
        "Esinhart Ohmiras",
        "Exogenic",
        "Eydoriane Cloudrider",
        "FakePresident Trump",
        "Farah Al Assad",
        "Faridah",
        "Fisto's Judgement",
        "Fleeny theYounger",
        "Franklin Underhill",
        "Franky Stien",
        "Freeto",
        "Gell Schereau",
        "Goro Nobunaga",
        "gritchack",
        "Gruara Ambrye",
        "Hadra Moot",
        "Haha Doodskop",
        "Hans toker",
        "Heilfr Cfidard",
        "Hippo117",
        "Hoe Hum",
        "Hollygun",
        "Honor Treecat",
        "Ilian Amarin",
        "Iliana Amphal",
        "ImArchy",
        "Iroha Ramalho",
        "Ismael Zambada Garcia",
        "ivan noskoov",
        "Iymyrr D'Harun",
        "Jace Firemind",
        "Jakaja Cain",
        "Jeff Jayson",
        "JFKen Imperia",
        "Jin mung",
        "Johan Vilhelmsson",
        "Johnny Trousersnake",
        "Jordan Atavuli",
        "Jordan Clarksonton",
        "Jordan Lafisques",
        "Kal Flindor",
        "Kalo en Chasteaux",
        "Katakuri Ramalho",
        "Kemalmus",
        "Ketldor Ashokan",
        "Khaelian Osiris",
        "Khan'nikki",
        "Kheironos",
        "Koursk",
        "Krab Star",
        "Kurt Knispel",
        "Larry Scuttlebutt",
        "Latif Noban",
        "Le Farf",
        "Le limier",
        "lei Sinulf",
        "Liloo Metarkonnen",
        "Lucius Servius",
        "Ludwig Timewax",
        "Maiandra",
        "makstomaks",
        "Malken Odunen",
        "Maruda",
        "Matt L Hendar",
        "Mc Crecket",
        "MechaJeb Kerman",
        "Meemee Weebus",
        "Mickey Ultama",
        "Mist Amatin",
        "Miws Vokan",
        "Mora Repsonme",
        "Morghul Olon",
        "Mr Amezes Oramara",
        "Myon Acryllic",
        "Myon PogChamp",
        "Myon Valestoft",
        "n-Kada Booya",
        "Nira Marie",
        "No Thing",
        "Noisy Pink Bubbles",
        "ob1canoby-OG ONLY-OB1",
        "Omnipotent Cortex",
        "OneMan DeathSquad",
        "Orice",
        "Overcheles",
        "Pabby Lasoya",
        "Paul Brinkhoff",
        "Paymaster General Sacrosanct",
        "PikkuLissu",
        "Price Point",
        "pscyho",
        "Queen Gaea",
        "Quinn Dorsey",
        "Rainear Xanatos",
        "Ralphy Ari",
        "Randy Antollare",
        "Rath Windblade",
        "rdmr",
        "redmanic",
        "Renalus Darwin",
        "Rob-Halford",
        "robert hunt1",
        "Rocinantae",
        "Rock Lobster Larry",
        "Rock Triel",
        "Rodger Mueller",
        "Roy Underhill",
        "Runoff",
        "rupert man",
        "Sam Caldwel",
        "Sarebey",
        "Schneemann",
        "Sevara",
        "Shadow Bogspor",
        "Shinn Fumimasa",
        "Shpuntik",
        "sidoradan Eginald",
        "Simo Kehveli",
        "Skye Raiden",
        "Skyline9982 Aucie",
        "Soft Night",
        "Sonto Mikakka",
        "sourcey1",
        "Spooky Azaphi",
        "Spooky Emabali",
        "Sprinkle's McGee",
        "SPT2",
        "Square Error",
        "stopdropandlol",
        "Stormborn Runoff",
        "Strata McHouse",
        "Surprise Dreads",
        "Teetee Weebus",
        "Tekno Hunter",
        "tenned ekul",
        "Thaiax Isu",
        "The Cincinnati Twiz",
        "Thelzar Calzahar",
        "Theodore James",
        "Thrain Greyrider",
        "Thraun Ravensoul",
        "Throck Wallace",
        "Thyme Trader",
        "Tohu Tohuwabohu",
        "TracKBalL",
        "Uppsala",
        "Urodela Andomer",
        "Valda Varugashi",
        "Vandamsel",
        "Vera McCoy",
        "Volp Elysian",
        "Wex Starstryker",
        "wiliam Aldent",
        "Wolf Doukas",
        "yaabaa Onnlin",
        "Yasmine72",
        "Zarik Arafax",
        "Zawahir",
        "Zhele Jamohrr",
        "zinox Yadekfic",
        "aboc cheeze",
        "Adam Zamoyski",
        "Adds Hendar",
        "Aegaeonos",
        "Aeleria Mikuyo",
        "Airaim",
        "Akhubkhan Darksky",
        "Alcoholic Satan",
        "Aleria Darwin",
        "Ambrosius Aurelianus",
        "angelfr",
        "Apostle McHouse",
        "Armos Dragoon",
        "Aurynn Elarik",
        "Ayu Kasenumi",
        "Bakkachan",
        "Barnabus Sanders",
        "BaseEight Chelien",
        "Bassdusche ZiggyX",
        "Bingo Bongoed",
        "Boot",
        "Burk DETEIS",
        "caleb ball",
        "Calypso72 303",
        "Candy Cough-Drop",
        "Cap Skor",
        "Capt Jack Daniels",
        "CeeCee Weebus",
        "Champagne Hennessy",
        "Chaplain''Dextomus",
        "Choc Starfish",
        "Chris Griffin",
        "Clam Chowdah",
        "Cmdr Stargazer",
        "Colt Sauer",
        "crowtree",
        "Daemon Hawke",
        "Dameonirus Marino",
        "Darklord Dvader",
        "Darklord Tarkin",
        "Dean Snow",
        "DexProcter Bedala",
        "Djorr",
        "Draco McHouse",
        "Draison Foul",
        "Duke Swackhammer",
        "Dusty Deninard",
        "Ejen Nailo",
        "Elimination2",
        "Ellse Kryan",
        "EmperorFry",
        "Entriri Crendraven",
        "Esinhart Ohmiras",
        "Exogenic",
        "Eydoriane Cloudrider",
        "FakePresident Trump",
        "Farah Al Assad",
        "Faridah",
        "Fisto's Judgement",
        "Fleeny theYounger",
        "Franklin Underhill",
        "Franky Stien",
        "Freeto",
        "Gell Schereau",
        "Goro Nobunaga",
        "gritchack",
        "Gruara Ambrye",
        "Hadra Moot",
        "Haha Doodskop",
        "Hans toker",
        "Heilfr Cfidard",
        "Hippo117",
        "Hoe Hum",
        "Hollygun",
        "Honor Treecat",
        "Ilian Amarin",
        "Iliana Amphal",
        "ImArchy",
        "Iroha Ramalho",
        "Ismael Zambada Garcia",
        "ivan noskoov",
        "Iymyrr D'Harun",
        "Jace Firemind",
        "Jakaja Cain",
        "Jeff Jayson",
        "JFKen Imperia",
        "Jin mung",
        "Johan Vilhelmsson",
        "Johnny Trousersnake",
        "Jordan Atavuli",
        "Jordan Clarksonton",
        "Jordan Lafisques",
        "Kal Flindor",
        "Kalo en Chasteaux",
        "Katakuri Ramalho",
        "Kemalmus",
        "Ketldor Ashokan",
        "Khaelian Osiris",
        "Khan'nikki",
        "Kheironos",
        "Koursk",
        "Krab Star",
        "Kurt Knispel",
        "Larry Scuttlebutt",
        "Latif Noban",
        "Le Farf",
        "Le limier",
        "lei Sinulf",
        "Liloo Metarkonnen",
        "Lucius Servius",
        "Ludwig Timewax",
        "Maiandra",
        "makstomaks",
        "Malken Odunen",
        "Maruda",
        "Matt L Hendar",
        "Mc Crecket",
        "MechaJeb Kerman",
        "Meemee Weebus",
        "Mickey Ultama",
        "Mist Amatin",
        "Miws Vokan",
        "Mora Repsonme",
        "Morghul Olon",
        "Mr Amezes Oramara",
        "Myon Acryllic",
        "Myon PogChamp",
        "Myon Valestoft",
        "n-Kada Booya",
        "Nira Marie",
        "No Thing",
        "Noisy Pink Bubbles",
        "ob1canoby-OG ONLY-OB1",
        "Omnipotent Cortex",
        "OneMan DeathSquad",
        "Orice",
        "Overcheles",
        "Pabby Lasoya",
        "Paul Brinkhoff",
        "Paymaster General Sacrosanct",
        "PikkuLissu",
        "Price Point",
        "pscyho",
        "Queen Gaea",
        "Quinn Dorsey",
        "Rainear Xanatos",
        "Ralphy Ari",
        "Randy Antollare",
        "Rath Windblade",
        "rdmr",
        "redmanic",
        "Renalus Darwin",
        "Rob-Halford",
        "robert hunt1",
        "Rocinantae",
        "Rock Lobster Larry",
        "Rock Triel",
        "Rodger Mueller",
        "Roy Underhill",
        "Runoff",
        "rupert man",
        "Sam Caldwel",
        "Sarebey",
        "Schneemann",
        "Sevara",
        "Shadow Bogspor",
        "Shinn Fumimasa",
        "Shpuntik",
        "sidoradan Eginald",
        "Simo Kehveli",
        "Skye Raiden",
        "Skyline9982 Aucie",
        "Soft Night",
        "Sonto Mikakka",
        "sourcey1",
        "Spooky Azaphi",
        "Spooky Emabali",
        "Sprinkle's McGee",
        "SPT2",
        "Square Error",
        "stopdropandlol",
        "Stormborn Runoff",
        "Strata McHouse",
        "Surprise Dreads",
        "Teetee Weebus",
        "Tekno Hunter",
        "tenned ekul",
        "Thaiax Isu",
        "The Cincinnati Twiz",
        "Thelzar Calzahar",
        "Theodore James",
        "Thrain Greyrider",
        "Thraun Ravensoul",
        "Throck Wallace",
        "Thyme Trader",
        "Tohu Tohuwabohu",
        "TracKBalL",
        "Uppsala",
        "Urodela Andomer",
        "Valda Varugashi",
        "Vandamsel",
        "Vera McCoy",
        "Volp Elysian",
        "Wex Starstryker",
        "wiliam Aldent",
        "Wolf Doukas",
        "yaabaa Onnlin",
        "Yasmine72",
        "Zarik Arafax",
        "Zawahir",
        "Zhele Jamohrr",
        "zinox Yadekfic",
        "aboc cheeze",
        "Adam Zamoyski",
        "Adds Hendar",
        "Aegaeonos",
        "Aeleria Mikuyo",
        "Airaim",
        "Akhubkhan Darksky",
        "Alcoholic Satan",
        "Aleria Darwin",
        "Ambrosius Aurelianus",
        "angelfr",
        "Apostle McHouse",
        "Armos Dragoon",
        "Aurynn Elarik",
        "Ayu Kasenumi",
        "Bakkachan",
        "Barnabus Sanders",
        "BaseEight Chelien",
        "Bassdusche ZiggyX",
        "Bingo Bongoed",
        "Boot",
        "Burk DETEIS",
        "caleb ball",
        "Calypso72 303",
        "Candy Cough-Drop",
        "Cap Skor",
        "Capt Jack Daniels",
        "CeeCee Weebus",
        "Champagne Hennessy",
        "Chaplain''Dextomus",
        "Choc Starfish",
        "Chris Griffin",
        "Clam Chowdah",
        "Cmdr Stargazer",
        "Colt Sauer",
        "crowtree",
        "Daemon Hawke",
        "Dameonirus Marino",
        "Darklord Dvader",
        "Darklord Tarkin",
        "Dean Snow",
        "DexProcter Bedala",
        "Djorr",
        "Draco McHouse",
        "Draison Foul",
        "Duke Swackhammer",
        "Dusty Deninard",
        "Ejen Nailo",
        "Elimination2",
        "Ellse Kryan",
        "EmperorFry",
        "Entriri Crendraven",
        "Esinhart Ohmiras",
        "Exogenic",
        "Eydoriane Cloudrider",
        "FakePresident Trump",
        "Farah Al Assad",
        "Faridah",
        "Fisto's Judgement",
        "Fleeny theYounger",
        "Franklin Underhill",
        "Franky Stien",
        "Freeto",
        "Gell Schereau",
        "Goro Nobunaga",
        "gritchack",
        "Gruara Ambrye",
        "Hadra Moot",
        "Haha Doodskop",
        "Hans toker",
        "Heilfr Cfidard",
        "Hippo117",
        "Hoe Hum",
        "Hollygun",
        "Honor Treecat",
        "Ilian Amarin",
        "Iliana Amphal",
        "ImArchy",
        "Iroha Ramalho",
        "Ismael Zambada Garcia",
        "ivan noskoov",
        "Iymyrr D'Harun",
        "Jace Firemind",
        "Jakaja Cain",
        "Jeff Jayson",
        "JFKen Imperia",
        "Jin mung",
        "Johan Vilhelmsson",
        "Johnny Trousersnake",
        "Jordan Atavuli",
        "Jordan Clarksonton",
        "Jordan Lafisques",
        "Kal Flindor",
        "Kalo en Chasteaux",
        "Katakuri Ramalho",
        "Kemalmus",
        "Ketldor Ashokan",
        "Khaelian Osiris",
        "Khan'nikki",
        "Kheironos",
        "Koursk",
        "Krab Star",
        "Kurt Knispel",
        "Larry Scuttlebutt",
        "Latif Noban",
        "Le Farf",
        "Le limier",
        "lei Sinulf",
        "Liloo Metarkonnen",
        "Lucius Servius",
        "Ludwig Timewax",
        "Maiandra",
        "makstomaks",
        "Malken Odunen",
        "Maruda",
        "Matt L Hendar",
        "Mc Crecket",
        "MechaJeb Kerman",
        "Meemee Weebus",
        "Mickey Ultama",
        "Mist Amatin",
        "Miws Vokan",
        "Mora Repsonme",
        "Morghul Olon",
        "Mr Amezes Oramara",
        "Myon Acryllic",
        "Myon PogChamp",
        "Myon Valestoft",
        "n-Kada Booya",
        "Nira Marie",
        "No Thing",
        "Noisy Pink Bubbles",
        "ob1canoby-OG ONLY-OB1",
        "Omnipotent Cortex",
        "OneMan DeathSquad",
        "Orice",
        "Overcheles",
        "Pabby Lasoya",
        "Paul Brinkhoff",
        "Paymaster General Sacrosanct",
        "PikkuLissu",
        "Price Point",
        "pscyho",
        "Queen Gaea",
        "Quinn Dorsey",
        "Rainear Xanatos",
        "Ralphy Ari",
        "Randy Antollare",
        "Rath Windblade",
        "rdmr",
        "redmanic",
        "Renalus Darwin",
        "Rob-Halford",
        "robert hunt1",
        "Rocinantae",
        "Rock Lobster Larry",
        "Rock Triel",
        "Rodger Mueller",
        "Roy Underhill",
        "Runoff",
        "rupert man",
        "Sam Caldwel",
        "Sarebey",
        "Schneemann",
        "Sevara",
        "Shadow Bogspor",
        "Shinn Fumimasa",
        "Shpuntik",
        "sidoradan Eginald",
        "Simo Kehveli",
        "Skye Raiden",
        "Skyline9982 Aucie",
        "Soft Night",
        "Sonto Mikakka",
        "sourcey1",
        "Spooky Azaphi",
        "Spooky Emabali",
        "Sprinkle's McGee",
        "SPT2",
        "Square Error",
        "stopdropandlol",
        "Stormborn Runoff",
        "Strata McHouse",
        "Surprise Dreads",
        "Teetee Weebus",
        "Tekno Hunter",
        "tenned ekul",
        "Thaiax Isu",
        "The Cincinnati Twiz",
        "Thelzar Calzahar",
        "Theodore James",
        "Thrain Greyrider",
        "Thraun Ravensoul",
        "Throck Wallace",
        "Thyme Trader",
        "Tohu Tohuwabohu",
        "TracKBalL",
        "Uppsala",
        "Urodela Andomer",
        "Valda Varugashi",
        "Vandamsel",
        "Vera McCoy",
        "Volp Elysian",
        "Wex Starstryker",
        "wiliam Aldent",
        "Wolf Doukas",
        "yaabaa Onnlin",
        "Yasmine72",
        "Zarik Arafax",
        "Zawahir",
        "Zhele Jamohrr",
        "zinox Yadekfic",
        "aboc cheeze",
        "Adam Zamoyski",
        "Adds Hendar",
        "Aegaeonos",
        "Aeleria Mikuyo",
        "Airaim",
        "Akhubkhan Darksky",
        "Alcoholic Satan",
        "Aleria Darwin",
        "Ambrosius Aurelianus",
        "angelfr",
        "Apostle McHouse",
        "Armos Dragoon",
        "Aurynn Elarik",
        "Ayu Kasenumi",
        "Bakkachan",
        "Barnabus Sanders",
        "BaseEight Chelien",
        "Bassdusche ZiggyX",
        "Bingo Bongoed",
        "Boot",
        "Burk DETEIS",
        "caleb ball",
        "Calypso72 303",
        "Candy Cough-Drop",
        "Cap Skor",
        "Capt Jack Daniels",
        "CeeCee Weebus",
        "Champagne Hennessy",
        "Chaplain''Dextomus",
        "Choc Starfish",
        "Chris Griffin",
        "Clam Chowdah",
        "Cmdr Stargazer",
        "Colt Sauer",
        "crowtree",
        "Daemon Hawke",
        "Dameonirus Marino",
        "Darklord Dvader",
        "Darklord Tarkin",
        "Dean Snow",
        "DexProcter Bedala",
        "Djorr",
        "Draco McHouse",
        "Draison Foul",
        "Duke Swackhammer",
        "Dusty Deninard",
        "Ejen Nailo",
        "Elimination2",
        "Ellse Kryan",
        "EmperorFry",
        "Entriri Crendraven",
        "Esinhart Ohmiras",
        "Exogenic",
        "Eydoriane Cloudrider",
        "FakePresident Trump",
        "Farah Al Assad",
        "Faridah",
        "Fisto's Judgement",
        "Fleeny theYounger",
        "Franklin Underhill",
        "Franky Stien",
        "Freeto",
        "Gell Schereau",
        "Goro Nobunaga",
        "gritchack",
        "Gruara Ambrye",
        "Hadra Moot",
        "Haha Doodskop",
        "Hans toker",
        "Heilfr Cfidard",
        "Hippo117",
        "Hoe Hum",
        "Hollygun",
        "Honor Treecat",
        "Ilian Amarin",
        "Iliana Amphal",
        "ImArchy",
        "Iroha Ramalho",
        "Ismael Zambada Garcia",
        "ivan noskoov",
        "Iymyrr D'Harun",
        "Jace Firemind",
        "Jakaja Cain",
        "Jeff Jayson",
        "JFKen Imperia",
        "Jin mung",
        "Johan Vilhelmsson",
        "Johnny Trousersnake",
        "Jordan Atavuli",
        "Jordan Clarksonton",
        "Jordan Lafisques",
        "Kal Flindor",
        "Kalo en Chasteaux",
        "Katakuri Ramalho",
        "Kemalmus",
        "Ketldor Ashokan",
        "Khaelian Osiris",
        "Khan'nikki",
        "Kheironos",
        "Koursk",
        "Krab Star",
        "Kurt Knispel",
        "Larry Scuttlebutt",
        "Latif Noban",
        "Le Farf",
        "Le limier",
        "lei Sinulf",
        "Liloo Metarkonnen",
        "Lucius Servius",
        "Ludwig Timewax",
        "Maiandra",
        "makstomaks",
        "Malken Odunen",
        "Maruda",
        "Matt L Hendar",
        "Mc Crecket",
        "MechaJeb Kerman",
        "Meemee Weebus",
        "Mickey Ultama",
        "Mist Amatin",
        "Miws Vokan",
        "Mora Repsonme",
        "Morghul Olon",
        "Mr Amezes Oramara",
        "Myon Acryllic",
        "Myon PogChamp",
        "Myon Valestoft",
        "n-Kada Booya",
        "Nira Marie",
        "No Thing",
        "Noisy Pink Bubbles",
        "ob1canoby-OG ONLY-OB1",
        "Omnipotent Cortex",
        "OneMan DeathSquad",
        "Orice",
        "Overcheles",
        "Pabby Lasoya",
        "Paul Brinkhoff",
        "Paymaster General Sacrosanct",
        "PikkuLissu",
        "Price Point",
        "pscyho",
        "Queen Gaea",
        "Quinn Dorsey",
        "Rainear Xanatos",
        "Ralphy Ari",
        "Randy Antollare",
        "Rath Windblade",
        "rdmr",
        "redmanic",
        "Renalus Darwin",
        "Rob-Halford",
        "robert hunt1",
        "Rocinantae",
        "Rock Lobster Larry",
        "Rock Triel",
        "Rodger Mueller",
        "Roy Underhill",
        "Runoff",
        "rupert man",
        "Sam Caldwel",
        "Sarebey",
        "Schneemann",
        "Sevara",
        "Shadow Bogspor",
        "Shinn Fumimasa",
        "Shpuntik",
        "sidoradan Eginald",
        "Simo Kehveli",
        "Skye Raiden",
        "Skyline9982 Aucie",
        "Soft Night",
        "Sonto Mikakka",
        "sourcey1",
        "Spooky Azaphi",
        "Spooky Emabali",
        "Sprinkle's McGee",
        "SPT2",
        "Square Error",
        "stopdropandlol",
        "Stormborn Runoff",
        "Strata McHouse",
        "Surprise Dreads",
        "Teetee Weebus",
        "Tekno Hunter",
        "tenned ekul",
        "Thaiax Isu",
        "The Cincinnati Twiz",
        "Thelzar Calzahar",
        "Theodore James",
        "Thrain Greyrider",
        "Thraun Ravensoul",
        "Throck Wallace",
        "Thyme Trader",
        "Tohu Tohuwabohu",
        "TracKBalL",
        "Uppsala",
        "Urodela Andomer",
        "Valda Varugashi",
        "Vandamsel",
        "Vera McCoy",
        "Volp Elysian",
        "Wex Starstryker",
        "wiliam Aldent",
        "Wolf Doukas",
        "yaabaa Onnlin",
        "Yasmine72",
        "Zarik Arafax",
        "Zawahir",
        "Zhele Jamohrr",
        "zinox Yadekfic"]
    start = time.time()
    data = asyncio.run(full_fetch(names))
    end = time.time()
    print(data)
    print(end - start)